# Generated by Django 2.0.2 on 2018-03-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foodfly_User',
        ),
    ]
